version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: simple-snmpd-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    user: root
    networks:
      - jenkins-network

  docker-dind:
    image: docker:dind
    container_name: simple-snmpd-docker-dind
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
    networks:
      - jenkins-network

  simple-snmpd-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: simple-snmpd-test
    ports:
      - "161:161/udp"
    environment:
      - SNMP_COMMUNITY=public
    networks:
      - jenkins-network
    depends_on:
      - jenkins

volumes:
  jenkins_home:
  docker-data:

networks:
  jenkins-network:
    driver: bridge
